import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className="">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="slider">
                <div className="slider-container">
                    <div className="slider-encart">
                        <div className="slider-logo"><img src="./img/logo.png" alt="Vival - Meillonnas" className="max-w-[300px]" /></div>
                        <div className="info-first"><p>10 ans d'expérience</p></div>
                        <div className="slogan"><p>Épicerie | Tabac | Presse à&nbsp;<span>Meillonnas</span></p></div>
                        <div className="slider-btn">
                            <a href="#" className="btn btn-primary xs-mr-10">Contactez-nous</a>
                            <a href="#" className="btn btn-primary">Localisez-nous</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}
