import Head from 'next/head'
import Image from 'next/image'
import Bricks from '../src/components/Bricks'
import Checkerboard from '../src/components/Checkerboard'
import Header from '../src/components/Header'
import Intro from '../src/components/Intro'
import Masonryboard from '../src/components/Masonryboard'

export default function Home() {
    return (
        <div className="">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Bricks />
            <Intro />
            <Checkerboard />
            <Masonryboard />
        </div>
    )
}
